paths:  
  /order/{orderId}/status:
    get:
      summary: get order status
      description: This API is for the buyer to get and track order status
      tags:
        - order status
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
          description: ID of order to get status
      security:
        BearerAuth: []
      responses:
        "200":
          description: "Order"
          content:
            application/json:
              example:
                orderId: "12345"
                status: "processing"
                expectedDeliveryDate: "2024-12-31T23:59:59Z"
        "404":
          description: "Order not found"
          content:
            application/json:
              example:
                message: "Order not found"
        "500":
          description: "Internal server error"
          content:
            application/json:
              example:
                message: "Internal server error"
  
  
    put:
      summary: update order status(admin)
      description: This API is for the admin to update the status of the order using socket.io
      tags:
        - order status
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
          description: ID of the order to be updated
      
      security:
        - BearerAuth: []
      requestBody:
        description: Order status update payload
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [pending, processing, shipped, delivered, on hold, cancelled]
                  example: processing
      responses:
        "200":
          description: Updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: string
                  status:
                    type: string
                  expectedDeliveryDate:
                    type: string
                    format: date-time
        "400":
          description: Invalid order status
          content:
            application/json:
              example:
                message: "Invalid order status"
        "404":
          description: Order not found
          content:
            application/json:
              example:
                message: "Order not found"
        "500":
          description: Internal server error
          content:
            application/json:
              example:
                message: "Internal server error"
      


components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
