/:
  get:
    summary: welcome endpoint
    responses:
      200:
        description: server running
      500:
        description: sorry

paths:
  /deleteuser/{userId}/:
    delete:
      summary: This API is for deleting certain user
      description: This API is for deleting certain user
      tags:
        - user
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: ID of the user to be deleted
      security:
        - BearerAuth: []
      responses:
        "200":
          description: User deleted successfully
        "500":
          description: Internal error server
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
